### PR TITLE
ADD: covid overview tracker

### PR DESCRIPTION
**Pull request by pratapvardhan**
I was experimenting with using jupyter notebook, pandas (data transformations), jinja2 (html, visual)
to create dashboards with fastpages. Bulk of visual heavy-lifting is in jinja2 and data with pandas.

Is the something you'd want to add?

image

### CODE REVIEW

**Comment by hamelsmu** [comment]
@pratapvardhan This is completely mind blowing.  I'm still trying to wrap my head around how you did this.  Would you be willing to write an official blog post / tutorial for https://fastpages.fast.ai/

**Comment by hamelsmu** [comment]
@pratapvardhan  looks like there are broken tags somewhere in your notebook, is this something you could fix?

https://covid19dashboards.com/covid-overview/

image

**Comment by hamelsmu** [comment]
@pratapvardhan I currently hid this from view from the main dashboard until it can be fixed.  Thank you!

**Comment by pratapvardhan** [comment]
I believe https://github.com/pratapvardhan/notebooks/commit/98ffa2390210cbb19bff7d9b9b1e47de68da10ea  this should fix it. This repos' Notebook uses the template from my repo. So, no code changes in this repo. Could you let me know if that works?

**Comment by hamelsmu** [comment]
@pratapvardhan That doesn't seem to fix it.  If you have docker installed on your computer, you can call `make build` followed by `make server` from the root of the repo to test the site locally.  

Happy to provide any help to get this up.  I'm really excited to have this on the page ..

**Comment by pratapvardhan** [comment]
@hamelsmu -- On windows docker, I could not see any posts on http://127.0.0.1:4000/. Here's the log, anything I'm missing?
```
$ make server
docker-compose down --remove-orphans || true;
Removing network covid19-dashboard_default
docker-compose up
Creating network "covid19-dashboard_default" with the default driver
Creating covid19-dashboard_fastpages_1 ... done
Creating covid19-dashboard_converter_1 ... done
Creating covid19-dashboard_jekyll_1    ... done
Creating covid19-dashboard_watcher_1   ... done
Attaching to covid19-dashboard_converter_1, covid19-dashboard_fastpages_1, covid19-dashboard_watcher_1, covid19-dashboard_jekyll_1
converter_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
fastpages_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
covid19-dashboard_converter_1 exited with code 1
covid19-dashboard_fastpages_1 exited with code 1
jekyll_1     | Successfully installed bundler-2.1.4
jekyll_1     | 1 gem installed
jekyll_1     | ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
jekyll_1     | Configuration file: /data/_config.yml
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |             Source: /data
jekyll_1     |        Destination: /data/_site
jekyll_1     |  Incremental build: disabled. Enable with --incremental
jekyll_1     |       Generating...
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |        Jekyll Feed: Generating feed for posts
jekyll_1     |                     done in 2.424 seconds.
jekyll_1     |  Auto-regeneration: enabled for '/data'
jekyll_1     |     Server address: http://0.0.0.0:4000/
jekyll_1     |   Server running... press ctrl-c to stop.
jekyll_1     | [2020-03-19 23:22:06] ERROR `/compare-country-trajectories/' not found.
```

**Comment by hamelsmu** [comment]
hmm try deleting everything in your `_posts` folder.  This is a very odd log message

**Comment by hamelsmu** [comment]
I"m also happy to set up some time to pair program if that is helpful!  Let me know!

**Comment by hamelsmu** [comment]
@pratapvardhan I think you fixed it?  Works for me locally now!  I'm unhiding it now 👍

**Comment by hamelsmu** [comment]
Ok its live https://covid19dashboards.com/covid-overview/ 

@pratapvardhan  Congrats 🎉  This is the coolest dashboard on the site!  I really want to understand how you did this?  It is amazing, really.  

Did you mockup the HTML via a template with any tools?  What was your process?  So cool!

**Comment by pratapvardhan** [comment]
@hamelsmu awesome! Will plan for a write up. HTML template was largely hand coded. In short, jinja2 template takes transformed data and gives the html output to be inserted back in.

I think, I managed to narrow the windows issue with few setup files. Will send a PR for that.

**Comment by hamelsmu** [comment]
That’s great would love to have you as a guest blogger on fastpages.fast.ai, but feel free to blog on your own too.  Either way this is really creative way to make cool charts that everyone should know about!

**Comment by pratapvardhan** [comment]
@hamelsmu -- so I manged to setup on windows after chaning the line endings from CRLF to LF for these two files `\_action_files\action_entrypoint.sh` and `\_action_files\word2post.sh` -- not sure how would like to fix this. git/code editors messes up with line endings.

**Comment by hamelsmu** [comment]
Hmm you are not the first person to raise this issue.  I am at a loss on
how to fix this for windows users... can you post about this in
forums.fast.ai so I can ask the community to help me?

**Pull request merged**
