### PR TITLE
add countries/table

### PR DESCRIPTION
**Pull request by jbduarte**

### CODE REVIEW

**Comment by hamelsmu** [comment]
Please fix conflicts some fixes were applied in this PR 

https://github.com/github/covid19-dashboard/pull/101

**Comment by hamelsmu** [comment]
Please remove extreanous file `.DS_Store`

**Comment by jbduarte** [comment]
> Please fix conflicts some fixes were applied in this PR
> 
> #101

Hamel I could not understand how to dress this

**Comment by hamelsmu** [comment]
Manually fixed conflicts on behalf of submitter in https://github.com/github/covid19-dashboard/commit/c89375f69d19ba2b7f7effac78c79b3ffb7876a1

**Pull request closed without merging**
