### PR TITLE
Merge Jbduarte's Notebook

### PR DESCRIPTION
**Pull request by hamelsmu**

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jbduarte The main concern I have is this chart is likely to cause more confusion that good.  This is because the number of cases is only discernable from the number of tests a country administers.  For example, South Korea had widespread testing, where the USA has really poor testing.   

I think a better denominator would be `#of positive cases per test`?   I have moved this notebook into the `_drafts` folder for now

**Comment by jbduarte** [comment]
For sure the number of cases is correlated with the amount of testing, But this true also for confirmed cases in absolute leves (like the ones you already posted comparing trajectories). For instance, looking in levels like you have now posted looks like China did a very poor job containing it when that is not the case. Another example, Singapore did a worse job than Japan. Not better. And we can see this form yesterday numbers. To go to the extreme, think about putting even small countries in the level graphs that is public, countries like Faroe Islands, they would not even show up in the levels plot but their situation is dire per capita (beds/ventilators are correlated with size of pop). I think this concern superseeds the number of tests one. Just yesterday I received an email from John Nelson from UW Madison asking for the plot because people were using it in a online presentation.

Moreover, there are countries that are were not testing a lot per capita but still see a huge increase in the number of confirmed cases.  It is just a matter of time until the number of cases in those countries that did not test in the begging see a huge surge in confirmed cases like it is happening everywhere now. And this is the right message. I am afraid that dividing by number of tests we are manipulating info more because we do not know correctly yet how # of tests connects with confirmed cases in a perfect way ( I saw in the our world in data and the correlation is there but weak). Also, you might do a lot of testing but with a wrong target  which will then lead us to think the true spread is low as well. I prefer to not play around in fixing the problem of inference of the population directly. I prefer to have the sample has it is and understand that there is sample uncertainty. People can then have their assumptions regarding testing or other issues and make proper inference (put confidence bands on our sample trajectories).

We could still do an another (in addition to the ones we already have) plot with:  (# Cases) / (# Tests X Population) 

Which is what you suggested cases / tests but scaling it by population. In this way, countries that have a low # cases / population ratio get low values and at the same time countries that have low cases / tests also have lower values given the same population size. What do you think?

As for deaths this concern is not an issue and still it makes much more sense to scale by population in my opinion.

**Comment by jbduarte** [comment]
On a second thought, after looking at the data we have on testing I think it is better not to do it by number of tests when comparing trajectories because:

- Data is not consolidated/centralized and there is a lot of mismeasurement in number of testing (much more so than in # of confirmed cases)
- We do not know exactly when the tests were made and timing is key when comparing trajectories.

**Comment by hamelsmu** [comment]
Ok thanks for discussing this.  Isn’t a confirmed case only possible when there is a test done first or is there another way people know of a confirmed case?


I feel like I need a second opinion on this one

@twiecki can you chime in with your opinion ?  The discussion centers around whether we should display a chart that shows cases / population, and I’m concerned that this statistic is too misleading because of the case count being tied to tests.  However, read the counter arguments above and let us know what you think 

Thanks

**Comment by jbduarte** [comment]
Dear Hamel,

It is only possible when the test is made, but results take time. And the tests can take different amount of days to get confirmation.

Also, note that your concern (which I think is correct) also applies to absolute number of cases (that is without scaling by population size).

J

**Comment by hamelsmu** [comment]
That’s true that the bias is also present in the total number of confirmed cases!  

I suppose the slope (which is the main thing people should pay attention to) could also change if a country begins to ramp up testing.  I think what people want to see is a flattening in this graph.  So I agree with you that this is the same problem

my question is, do you think this proposed chart is mainly a function of how well a country tests per capita rather and less about actually illuminating differences in healthcare per country?  If so the chart may suggest the opposite of what is true?  Or in other words what is the story to take away from this chart, what can we really learn from it?

I’m still thinking about your suggestion (#of cases x Tests) let me think about that one.  

Note:  perhaps we need to put a disclaimer on some of the other charts too as I agree on your points of biases.  

@dansbecker would appreciate your opinion on this thread as well

**Comment by jbduarte** [comment]
> do you think this proposed chart is mainly a function of how well a country tests per capita rather and less about actually illuminating differences in healthcare per country?
> 
No. There are countries such as Japan that are not testing a lot per capita and are having low number of cases. On the other extreme, in Spain they are testing only people that are being internalized in hospitals and cases do not stop going up very fast.

> Or in other words what is the story to take away from this chart, what can we really learn from it?
> 
The main take away is that high slopes in this plot are more worrisome than without scaling per capita, because the size of population correlated to the number of beds/ventilators. (think about how China was able to reallocate a lot of resources from the rest of the country (doctors/nurses) to the outbreak region. A small country cannot do that. And if per population is high there is no way can do that either because all hospitals are busy.

**Comment by jbduarte** [comment]
Just one last thing and I am repeating myself already:

50 cases in Portugal are way more worrisome and 50 cases in the US.

**Comment by jbduarte** [comment]
Than*

**Comment by hamelsmu** [comment]
@jbduarte @dansbecker @twiecki the draft version of this chart that we are currently discussing can be previewed here https://covid19dashboards.com/covid-compare-permillion/

It is currently hidden from the main page to allow us to discuss a bit more

**Comment by dansbecker** [comment]
@hamelsmu I've been quite worried about the issue you're bringing up, that viewers conflate the number of tested positives with the population infection rate. Here a couple things to consider:

Here's an interesting fact:

1. The fraction of tests in the US that come back positive shows no meaningful trend over time. It's varied between 10.5% and 12% for 8 of the 9 days on which I calculated it (The one day outside that range was over 30%, which I don't have a good explanation for).

If we agree infections in the US have increased, positive rates of tests are a poor proxy for the population infection rate. 

So I'd disfavor showing a graph that plots positive test rates over time or across countries.

2. Changes in test availability will cause misleading growth rates over time. If 10% of a population is infected and you test 100 of them today, you'll get 10 positive cases. 
If you test 200 of them tomorrow, you'll get 20 positive cases. So you'd report 100% day-over-day growth rates in positive cases, even in the absence of infection rate increases. So far, I'm not aware of countries who have increased testing quickly enough for this to be a big source of error, and it's more of a concern for future calculations. 

I tend to trust within-country growth rate comparisons calculated so far.

3. Comparison of positive tests across countries likely aren't reliable. For instance, this notebook shows the UK has 25% as many cases per million as S. Korea.... while having the same number of deaths per million. I think we'd agree the difference is that S. Korea is catching a larger fraction of cases due to differences in testing.

Because of the time between infection and death, death rates are more directly a proxy for infections a few weeks ago (as well as quality of medical care). But I think per-capita deaths are the best proxy for cross-country comparisons at any point in time, because they're less subject to variation driven by test availability.

**Comment by jbduarte** [comment]
I agree. 

Deaths per capita are our best bet at measurement of the true state of the cover crisis.

**Comment by jbduarte** [comment]
I agree.

I think we could put it in an appendix with a large warning. (this is just to keep track and not draw conclusions, hoping that the curves will flatten)

What do you think?

**Comment by dansbecker** [comment]
@jbduarte There was a Medium post (which I can find again if you're interested) that used

`infection rate = # deaths / case fatality rate` to estimate the infections 2 weeks prior. 

Then they use estimated growth rates over the 2 weeks to estimate current infection rates.

I think they have a Jensen's inequality problem with using a mean or median time to death (2 weeks) as the time they extrapolate forward from. But it still strikes me as an overall reasonable strategy. 

You may have all the data already to do a similar calculation. What are your thoughts about showing something like that (being transparent about how you are calculating infection rates?)

It'd also be interesting to compare that to measurements of positive test cases. Maybe you don't show it, but I'd be fascinated to see a scatter of 

Infections per Million using method described above VS Cases per million

The thing I'd be looking for is which countries do we think are catching a large fraction of their cases. The shortcoming of that approach is that it's only interesting to the extent our calculation of infection rate is reasonable.

**Comment by jbduarte** [comment]
@dansbecker <https://github.com/dansbecker> Very interesting exercise. I think it could provide a statistic that allow to better infer for the population infection rate.  One thing we need to make sure we get right is the median time from testing positive to death. In Italy I saw that the health authority reported a median of 8 days from first symptoms to death. We need to know is from testing positive to death. Do you know where to find this?

I would be happy to do this analysis for sure.

J

**Comment by romanofoti** [comment]
Weighing in a little late, perhaps, but I agree that the number of deaths is likely the most meaningful measure of the spread of the contagion, since it is the only element that should be relatively invariant to most confounding factors.

Nevertheless, I think some good information can be drawn from the number of confirmed cases, so putting it into the appendix sounds like a good idea to me. It is also rather likely that testing procedures will tend to improve and become more standardized and widespread over the next few days, so that info may become more relevant later on.

**Comment by jbduarte** [comment]
@dansbecker <https://github.com/dansbecker> forget what I wrote. From first symptoms sounds about right for this exercise.

**Comment by hamelsmu** [comment]
thanks @romanofoti ❤️ 

Discussed changes have been made: https://covid19dashboards.com/covid-compare-permillion/

Please let me know if anything should be changed.  The visualization is also now listed on the home page.

**Comment by jbduarte** [comment]
@dansbecker <https://github.com/dansbecker> I will do assuming one week and two weeks as robustness.

J

**Comment by hamelsmu** [comment]
@dansbecker @jbayardo re: Estimating case counts using mortality, We have an existing analysis that does this for the US that may be helpful courtesy of @jwrichar  https://covid19dashboards.com/covid-19-us-case-estimation/

**Comment by jbduarte** [comment]
@dansbecke I did what you suggested. Its at https://github.com/jbduarte/covid19-dashboard/blob/estimating_infected_nb/_notebooks/estimating_%23infected.ipynb <https://github.com/jbduarte/covid19-dashboard/blob/estimating_infected_nb/_notebooks/estimating_#infected.ipynb>

Very scary.

J


https://github.com/jbduarte/covid19-dashboard/blob/estimating_infected_nb/_notebooks/estimating_%23infected.ipynb

**Comment by dansbecker** [comment]
@jbduarte Those numbers aren't good, but aren't a total surprise to me. Here are the guesses of fraction reported by some [experts](https://fivethirtyeight.com/features/infectious-disease-experts-dont-know-how-bad-the-coronavirus-is-going-to-get-either/) and by [non-experts](https://twitter.com/dan_s_becker/status/1238594237618245632). Those links I just sent are all for the US.

I interpret your numbers as lying somewhere between the consensus of experts and the consensus of non-experts... being closer to the experts. 

Anyway... do you believe your analysis, or think it has some critical shortcoming?

Planning to publish that?

I find it very interesting. Thank you for creating and sharing the analysis with me.

**Comment by jbduarte** [comment]
@dansbecke Thanks for all the feedback.

I do believe it. It crucially depends on 3 things:
1-  the average time duration from symptoms do death
2-  the estimate growth rate of infected during that period. 
3- the CFR being actually close to IFR

The estimated growth rate I am not too worried about since it is stationary (hence classical inference is valid and we get ergodicity for the mean and variance). Hence, as the sample size increases we should get a good estimate of g.  

I am more worried about the CRF as a proxy to IRF. Other than that, at the moment I do believe this is a sensible approach.

J

**Pull request merged**
