### PR TITLE
Add world-news dashboard, minor updates to ICU projections dashboard

### PR DESCRIPTION
**Pull request by artdgn**
### Changes:
- Add world-news dashboard for significant changes in last 10 days:
  - Large positive and negative changes in transmission rates (new waves, slowing waves),
ICU need, cases and deaths
  - World-stacked plots for active and recovered (past and 30 days projection)
- Updates to ICU projections dashboard: add emoji flags, update helper

### CODE REVIEW

**Comment by hamelsmu** [comment]
Thanks @artdgn I find this dashboard to be a bit cluttered and hard to digest.  

- How automated is the good and bad news with commentary?
- Can you have an executive level summary with commentary at the top?  with the Green and Red circles.  Can you have a legend for these?
- Can you put the methodology and supporting charts etc in a appendix so users can focus on your high level message

Tagging @dansbecker for further review

**Comment by artdgn** [comment]
> Can you have an executive level summary with commentary at the top? with the Green and Red circles

Great idea! I've added the flags into the header titles - so now one glance at the TOC provides a summary of everything (if the viewer is familiar with their flags of interest). They're still clickable, which leads to the tables and graphs for each section.
Bonus: it's a great way to learn unfamiliar flags :)

> Can you have a legend for these?

Can you give me some examples of what's unclear / confusing? I wouldn't want to add any additional clutter of explaining self-explanatory names, so would prefer to just name things better if they're not clear.

> How automated is the good and bad news with commentary?

Not sure what you mean.. everything is automated. There are specific criteria for being in any of the "news groups" which are used for filtering countries into groups and sorting them within groups.

**Comment by artdgn** [comment]
@hamelsmu, hope you're not too busy.

Here's a live version of the same code and content (with slight differences in explanation texts): https://artdgn.github.io/pages/covid-news/ from my repo. FWIW I have been following and using it in the last week, and I find it to be a good source of new information I wouldn't be aware of otherwise.

This has been open for a while now with multiple updates from me, but no feedback. Is there anyone else perhaps that can have a look?

**Comment by hamelsmu** [comment]
Hi @artdgn I am on vacation for a couple of weeks.   This dashboard will take time to review as there is an incredible amount of information here.  It might take me a really long time to review something like this so I will have to rely on help, unfortunately.    If this was more simple I could have reviewed easily but I think this deserves a bit more attention 

Sorry for the delay, glad to see that you have made something in the meantime

**Comment by hamelsmu** [comment]
Perhaps @anomal might be willing to take a look and review this

**Comment by hamelsmu** [comment]
Not stale

**Pull request merged**
