### PR TITLE
Case count estimation notebook

### PR DESCRIPTION
**Pull request by jwrichar**
A new notebook to potentially add to your site.

The MCMC runtime is about 3 minutes -- it's tough to reduce that to get good enough model results.  If that's too long, would it be possible to execute the notebook less frequently?

I left the 'image' blank for now.  Let me know if you need a screenshot.

Thanks!

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jwrichar some suggestions to make this more approachable:

- Can we promote your case estimates to the top, and the other stuff to the bottom?  Its better to lead with your estimates and leave the technical stuff in an appendix

- Can we think of a way to present this information?  I would argue a table is better than this graph?  Four columns  (1) Observed, (2) Lower bound Estimate, (3) Point Estimate (4) Upper bound Estimate?  or something like this? 
- The scale on this graph is overwhelmed by some outliers, so it doesn't present well. 

I can help you make an interactive chart that zooms into each state, as that might be more interesting for a visual.  

Let me know your thoughts.

**Comment by jwrichar** [comment]
@hamelsmu thanks for the feedback.

+ I agree with you about the re-ordering.  I think (1) overall US counts, (2) summary by state, (3) testing volume vs. under-reporting plot
+ I like the idea of adding a table -- I have one on my internal version that's something like (1) observed, (2) estimated, (3) % increase, (4) # tests per million -- and then I can add the upper/lower on the estimates
+ What did you have in mind for an interactive chart?  A map?  I'm not a python plotting expert, so whatever recommendations you have would be helpful!
+ I don't mind leaving the current statewise plot because it allows somebody to quickly scan and see which states might be way off (e.g., New Jersey!).  I can change it to log scale.

Thoughts?

**Comment by jwrichar** [comment]
Okay, take a look at the changes I made:

+ Rearranged so the logical flow is better
+ added a table that summarizes the state-wise counts

I still think there may be room for a fancy interactive map / viz.  LMK your thoughts.

**Comment by hamelsmu** [comment]
Thanks, getting closer, I think

Consider changing the title to something that really highlights the cool part of this visualization, like "How many cases of COVID-19 does your state really have?"

And then put a description at the top that motivates this report, such as - 

>Total case counts are based on the number of administered tests that are positive, however, not everyone is tested so this number is very biased.   In this analysis we use X technique to estimate the true number of cases per state

Consider formatting `Total for the United States on {Date}` as markdown header, as it's not too pretty.  You can achieve this like this

```py
from IPython.display import display, Markdown, Latex
display(Markdown('*some markdown*))
```

image


Hide this cell with `#hide_input`
image


Can we format the percentages in the table?  
image

I can adjust the table CSS / font size to be smaller so it fits without scroll

Seeing this table in this way, naturally inclines me to want to put a color-coded map of the US, where by you click on the state and it filters something like your observed vs. estimate chart.  But not sure how the observed vs. estimate chart is helpful, at the moment.  

This chart still leaves something to be desired, I think putting this on a log scale might actually be decieving / misleading b/c of the confidence intervals.   What is the potential story from this chart?  

image

Thanks

**Comment by jwrichar** [comment]
Addressed the comments.  Thanks for taking the time to go through the notebook.

Regarding the state-wise case plot, I agree that it's not all that useful now that the table is in place.  It's really only valuable to pick up on outliers, but now that's also doable with the table.

I can take a look at putting a clickable U.S. map (color-coded by predicted case volume?), but maybe for now we just remove the plot.

**Comment by hamelsmu** [comment]
I'm going to go ahead and merge this but this will be in a hidden state, as I have some more questions

What does the mortality rate have to do with this analysis?  I thought we are predicting total cases?

image


Don't the numbers seem a bit low to you?  Are we sure there isn't something off here?  Just  want to check

**Comment by hamelsmu** [comment]
I committed these changes to master (but the notebook is hidden for now) via https://github.com/github/covid19-dashboard/pull/59

Please pull and submit a fresh PR for further changes.  I had to make some commits on top of yours to fix some issues.

**Pull request closed without merging**
