### PR TITLE
Added visualisations for Africa, America, Asia-Pacific and Europe

### PR DESCRIPTION
**Pull request by Martin-Boehler**
Hello everyone, this is my second try of the (not merged) pull request #288.

Regarding the feedback from @hamelsmu, I inserted my new visualization of Europe into the existing dashboard of the US instead of creating a new one. I have inserted the new charts below the existing animated chart of the US and above the description.

Regarding the feedback from @snario, I now included the whole world. For better comparison, I have divided this into 4 separate charts (Africa, America, Asia-Pacific and Europe) and I added a table of content.

My charts are not animated like the existing chart of the US, but they are interactive. And I also changed the title a bit and expanded the author/reference section - hope that's okay

Please let me know what I can change or improve :)

Best regards,
Martin

### CODE REVIEW

**Comment by hamelsmu** [comment]
@Martin-Boehler could you also add a chart similar to yours for the US by state?  It might be better to replace the chart in the beginning with your format, and move the original animated version to the appendix.

**Comment by Martin-Boehler** [comment]
Hello everyone, sorry for the merge conflict... I suspect that the structure has changed too much due to the shift of the animation to the appendix...

As requested, I added my static format also for the states of the US (as the first graphic) and moved the animated version down.

Please let me know what I can change or improve :)

Best regards,
Martin

**Comment by hamelsmu** [comment]
I think you can take off the points (the dots) as they are cluttering the visualization and just have the line

image


You can also resolve the conflicts yourself.  Steps to resolve the conflict:

1. Save a copy of your notebook somewhere else (THIS IS REALLY IMPORTANT)
2. Merge the master branch of your repo into your local branch

```
git remote add upstream git@github.com:github/covid19-dashboard.git
git fetch upstream
git pull upstream master
```

If this  doesn't work, I suggest using Google to find out how to update your branch to be up to date with this repo.  

3.  replace the conflicted Jupyter notebooks with your copy

```
git mv <your copy>  _notebooks/
```

4.  add and commit this notebook to your branch

**Comment by Martin-Boehler** [comment]
Hello, I was able to resolve the merge conflict using your instruction - thank you very much :)
I also removed the cluttering points.

Please let me know what I can change or improve :)

Best regards,
Martin

**Comment by hamelsmu** [comment]
Great work @Martin-Boehler I created a conflict myself so I Had to merge your commits via https://github.com/github/covid19-dashboard/pull/311

@all-contributors add @Martin-Boehler for content

**Pull request closed without merging**
