### PR TITLE
confirmed-vs-growth-rate

### PR DESCRIPTION
**Pull request by elsonidoq**
Couldn't do the animation, but at least we have the scatter plot.

It's my first time using altair. Let me know if there's anything I should adapt

### CODE REVIEW

**Comment by elsonidoq** [comment]
image
This notebook seems to be failing on running.

**Comment by hamelsmu** [comment]
1. You have some spelling errors `Understand how well are the countries standing up, what countrie are accelerating the most?`

2. Can we think of a better title to differentiate this dashboard from others?  We have lots of dashboards on growth rates - what does this one show that is different?

3.  It is not immediately clear what the axis means, and I actually don't understand how to read this chart.  This needs to be polished up a bit

image

4. Put your findings (bullet points) **below** your chart.  People should see the chart first.  

5. Consider putting your graph about Latin America at the top of the dashboard, and renaming your dashboard to be about Latin America?  That could be your unique angle.  This is just a suggestion.  You could move the "all countries" to an appendix.  

Thanks.  BTW I just added a [Contributing Guide](https://github.com/github/covid19-dashboard/blob/master/CONTRIBUTING.md) that has some links on how to preview this locally incase that is helpful.

**Comment by elsonidoq** [comment]
Hi @hamelsmu! I made several changes. What do you think now?

**Comment by elsonidoq** [comment]
Hi @hamelsmu!! Thanks for your great feedback! I made several changes, what do you think of it now?

**Comment by hamelsmu** [comment]
- Title is confusing.  Is your visualization only showing that `Argentina declared mandatory isolation with just ~100 confirmed cases`?  Think about this more carefully.  Is this about Argentina?  If so, the first chart doesn't look like it.

- what is the unit of`t` is it a day?  Is there anything problematic with this unit of measurement?  Perhaps some kind of smoothing can make these visualiztion look less like spaghetti

- Your Y-axis should not be labeled the exact same as your x axis if they are different metrics.  
- Your "for example italy has 1.14 growth rate" is going to get out of date as the data is updated?
- I'm weary of just having this dashboard with some kind of findings sectoin as that may get out of date as the data is refreshed.  

If you find that this feedback is too cumbersome, I totally understand.  Don't let it stop you from publishing it on your own site if you haven't already with fastpages.  

Thanks for listening to the feedback

**Comment by elsonidoq** [comment]
Thanks for the feedback Hamel!

**Comment by hamelsmu** [comment]
Totally understand 🙇  Thank you

**Comment by hamelsmu** [comment]
@all-contributors add @elsonidoq for fighting the good fight

**Pull request closed without merging**
