### PR TITLE
Update overview chile

### PR DESCRIPTION
**Pull request by alonsosilvaallende**
Thank you very much. I didn't know we can do that. I have programmatically generated the markdown for the graphs with zero deaths.

### CODE REVIEW

**Comment by alonsosilvaallende** [comment]
Thank you very much. Would you consider moving it back to the dashboards? 
Thank you.

**Comment by hamelsmu** [comment]
Hello @alonsosilvaallende I think your charts need one more adjustment:

Daily confirmed deaths & cases need to be driven by a dropdown list instead of printing N charts to the dashboard, similar to what you are doing with the Evolution* charts.  I think that's the only change needed to turn this dashboard on!  

Thanks

**Comment by alonsosilvaallende** [comment]
Thank you, Hamel. Actually, I was thinking something along the lines of the [NYTimes](https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html) where you can check all the states. Otherwise, you would need to select one-by-one all the states from the dropdown menu to get a general view. But I can made the change you propose if you want to.

**Comment by hamelsmu** [comment]
Sure that would work too

**Pull request merged**
