### PR TITLE
overview-us use nytimes source #159

### PR DESCRIPTION
**Pull request by pratapvardhan**

### CODE REVIEW

**Comment by pratapvardhan** [comment]
Thanks you @nytimes @albertsun for the rescue! 🙏

**Comment by hamelsmu** [comment]
Thanks for the update!

**Comment by pratapvardhan** [comment]
@hamelsmu -- I just noticed I didn't remove " Warning: US data is currently not available. Data for US has not been updated since 3/23/2020." -- to avoid rework. Are you already on it or would like me to send in a fix?

**Comment by hamelsmu** [comment]
I'll do it

**Pull request merged**
