### PR TITLE
Changed text to consistent spelling of COVID-19

### PR DESCRIPTION
**Pull request by vladpke**

### CODE REVIEW

**Comment by hamelsmu** [comment]
@vladpke if you could resolve conflicts much appreciated

**Comment by vladpke** [comment]
Oh, there weren't any conflicts earlier. Must've happened because of a recent commit. I'll take a look

**Comment by vladpke** [comment]
Looks like it's too complex. I'll revert, merge new commits from upstream and recommit.

**Comment by hamelsmu** [comment]
ok sorry about thanks please tag me by name and I will try to merge quickly

**Comment by vladpke** [comment]
@hamelsmu Done! :)

**Pull request merged**
