### PR TITLE
Add chart for positive test results by State

### PR DESCRIPTION
**Pull request by Crissman**
With the rapid increase in testing, it's difficult to see how the percentage of the population with COVID-19 is changing. The percentage of tests which are positive is useful to see this.

Added a chart to display.

### CODE REVIEW

**Comment by hamelsmu** [comment]
@Crissman One concern I have is that it is hard to read this chart, perhaps something a bit more interactive will help people find their state?  Here is an example https://covid19dashboards.com/compare-country-trajectories/

**Comment by hamelsmu** [comment]
Another concern I have, that is worth discussing is the metric itself.  Positive percent seems like it could be biased depending on testing procedures, for example only testing the sick, etc.  

I'll let @dansbecker provide some input on this one as one of the wonderful peer reviewers that we have for this project

**Comment by dansbecker** [comment]
In theory, I find `% of tests positive` a useful metric to help understand whether an increase in positive cases is driven by increased testing or by increased infection.

But to use the metric in that way, I'd want to look at % positive and number of infections side by side. Either one in isolation is less useful than the two next to each other.

This suggests the problem that @hamelsmu alluded to, that there may be too much information at once for someone to interpret the graphs. If you can do something interactive like Hamel suggested, I think that helps a lot. And you could still show these side-by-side.

But here's my much bigger concern:
I've seen graphs of positive rates before where positive rates grow above 100%.

I think it's a data alignment problem. The reported positives represent cases that were confirmed positive on a given day. But it takes days after a test is conducted to confirm it is positive. The number of tests corresponds to tests conducted that day. 

So the positives reported on any given day aren't drawn from a population described by total tests that day.

There are some surprising things in this graph, and I think the data misalignment is the explanation:

image

For example, Iowa has rates above 50% for a couple days. Then the line disappears, and then starts again at a rate below 20%. Are there missing days because no tests happened those days or because the calculated rate was 100%. I also don't see Michigan, Arizona or Rhode Island in the chart. Those are states where I've previously "positive rates" above 100%

What were your selection criteria were for including a state in the graph? 

If those were dropped because they had positive rates >100%, it makes me worry about whether similar problems contaminate calculations that ended up in a plausible range.

**Comment by hamelsmu** [comment]
@zachmayer emailed me privately with something that might be helpful

> Good data here: https://data.world/covid-19-data-resource-hub/covid-19-case-counts/workspace/file?filename=COVID-19+Cases.csv

> Their data quality grade is helpful too: https://covidtracking.com/about-tracker/#data-quality-grade

image

@all-contributors add @zachmayer for maintenance

**Comment by Crissman** [comment]
Thanks for the feedback. I'll work on the selector for States, and then try adding another graph that superimposes total and positive cases with the positive test percent for a selected State.

**Comment by hamelsmu** [comment]
I'll close this for now, but please reopen this when you are ready!  Or feel free to open afresh PR whichever is most convenient for you.  

Thanks allot for contributing , look forward to your submission

**Pull request closed without merging**
