### PR TITLE
Change reference to right column

### PR DESCRIPTION
**Pull request by alonsosilvaallende**
Sorry for the inconvenience. The data source added a new column, so now I changed the reference to point to the right column. Please, could you consider moving it back to the dashboards?
Let me know if there is any problem or if I need to modify something else.
Thank you.

### CODE REVIEW

**Comment by hamelsmu** [comment]
Looks like your notebook is still ill defined, with charts looking like this in some places

image

your notebook remains deprecated.  Please review your notebook carefully before submitting

**Comment by alonsosilvaallende** [comment]
Thank you for your concerns but that’s because there are zero deaths in those regions at the moment. What do you suggest to put instead so that it’s updated automatically if there are deaths in those regions in the future?

**Comment by hamelsmu** [comment]
Can you dynamically generate the headings and the charts based upon what is available?  I thin you can programmatically generate markdown in Jupyter as well by the way.

**Comment by alonsosilvaallende** [comment]
Hi Hamel,
I have programmatically generated markdown in Jupyter (I didn't know we could do that). About the headings and the charts I didn't manage to do it with Altair (the plots are interactive). I have done another pull request #372 
Let me know if you know how to generate the charts with Altair without doing them by hand, and any other changes.
Thank you very much.

**Pull request merged**
