### PR TITLE
save fig

### PR DESCRIPTION
**Pull request by jbduarte**

### CODE REVIEW

**Comment by hamelsmu** [comment]
Please remove extreanous file `.DS_Store`

**Comment by hamelsmu** [comment]
@jbduarte would you be ok with this just remaining a static image that never changes?  Altair has complicated dependencies with regards to saving figures. https://altair-viz.github.io/user_guide/saving_charts.html#saving-altair-charts

If that is ok, feel free to close this PR

**Comment by hamelsmu** [comment]
Actually, nevermind lets figure out how to make it work -- I take that back, since Altair is now being used everywhere on this site.  

If you could fix conflicts and remove the offending file from this PR that would be helpful

**Comment by jbduarte** [comment]
The only conflict is related with the altair visualization.

**Comment by hamelsmu** [comment]
Hi @jbduarte you can resolve conflicts by selecting which changes you would like to apply, depending on your IDE there are tools for managing this.  The Review NB app will help you see where the conflicts are.  If you need help how to resolve conflicts in git let me know, I can do this for you this time, but this is something you can fix yourself, albiet this is one of the pains with Jupyter Notebooks

**Comment by hamelsmu** [comment]
Its actually not intuitive to resolve conflicts in GitHub with Jupyter notebooks, I'll see if I can find an article or something that can help, its because of all the metadata and everything ...

**Comment by hamelsmu** [comment]
Applied these changes and resolved conflicts via https://github.com/github/covid19-dashboard/commit/64c24f69cc6b190a1695c8b1c3eeb8a7eca63b3d

Could not merge this PR due to conflicts.

**Comment by jbduarte** [comment]
Yes that would be great. Thank you so much.

I noticed that most of it was about metadata and records of duration of running things.

**Pull request closed without merging**
