### PR TITLE
fixed country name

### LINKED ISSUE #643: Canada variants of concern dashboard should use Greek labels instead of country names
https://github.com/github/covid19-dashboard/blob/master/_notebooks/2021-04-03-canada-variants-of-concern.ipynb should use the [World Health Organization (WHO)'s Greek labels](https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/) "Alpha", "Beta", "Gamma" instead of "UK", "South Africa", "Brazil", respectively.

### PR DESCRIPTION
**Pull request by KamalSinghKhanna**
fixes #643 
I have changed country name

### CODE REVIEW

**Comment by anomal** [comment]
@KamalSinghKhanna Please run the Jupyter notebook and webpage on your local machine to test. There is an error.

**Comment by KamalSinghKhanna** [comment]
Do I now have to change the names of the countries (uk, sa, br) with Alpha, Beta , Gamma in the line below.
#hide_input
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_Alpha)

#hide_input
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_Beta)

#hide_input
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_Gamma)

**Comment by anomal** [comment]
You need to change https://github.com/github/covid19-dashboard/blob/master/_notebooks/canada_voc.py

**Comment by anomal** [comment]
The country names for the variants have been changed to the Greek letters now for the graphs, but there are still some problems.
- The notebook header "Canada variants of concern (VOC) growth per province or territory" has been truncated to "nts of concern (VOC) growth per province or territory"
- The secondary header "Cumulative cases" now shows code instead of the graphs:
> hide_input
> figlineprov
- Under the secondary header "Tables", the country names are still showing.

Please run fastpages on your local machine to test how the final webpage looks like, and compare it to https://covid19dashboards.com/canada-variants-of-concern-voc/

**Comment by anomal** [comment]
1. When I run fastpages locally, it shows `### B.1.1.7 (Alpha variant)` instead of a [third-level header](https://covid19dashboards.com/canada-variants-of-concern-voc/#B.1.1.7-(UK-variant)). The same applies to Beta and Delta.

canadavoc-demo

2. You can also add your name as an additional author.

**Comment by anomal** [comment]
Now there is an error when I try to run the Jupyter notebook.

**Comment by KamalSinghKhanna** [comment]
I am still working,

**Comment by Al-cpu-cyber** [comment]
Want to work on it again

**Comment by KamalSinghKhanna** [comment]
yes I want to work.

**Comment by KamalSinghKhanna** [comment]
I have made some changes, can someone review it ?

**Pull request closed without merging**
