### PR TITLE
Brazil flatten the curve

### PR DESCRIPTION
**Pull request by cleberjamaral**
This work is trying to show a "flatten the curve" graph using ICU data. Information about ICUs including how many are available are estimated using data from multiple sources. Using a scientific study the number of patients that should need ICU is also estimated. Finally, a graph of active cases is compared with lines that represents total ICUs and available for covid-a9 patients.

### CODE REVIEW

**Comment by cleberjamaral** [comment]
I just realized an important error in considering % of active cases instead o % of new cases for the ones that could need ICU. Another thing that should be improved is about this 12% which is based on the worst case reported regarding Italy. For this last point it would be better a different representation using the referred paper it can vary largely, from 1 to 12%, actually. The mean is supposed to be around 5% of the cases. The fact is that Brazil [struggle to publish this data](https://brasil.elpais.com/brasil/2020-04-28/sem-transparencia-sobre-fila-para-utis-justica-opera-para-garantir-atendimento-a-pacientes-de-covid-19.html), recently it was published a law to obligate hospitals to publish ICU occupancy data. The best to do is giving good approximations.

**Comment by hamelsmu** [comment]
can these charts be incorporated into an existing page rather than being on its own?

**Comment by cleberjamaral** [comment]
Hi Hamel, sure but do you have anyone in mind? Unfortunately it is too specific and with hard coded Brazilian data. I am planning to make it by states adding a selection box. It will make it a bit richer. Please, let me know which place it is more suitable. Also feel free to reject it, I acknowledge it is far under the level of other analysis.

**Comment by cleberjamaral** [comment]
Wrong assumptions. To do this: (i) I should consider the average time patients spend in ICUs adding up to them about 5% of the new cases per day. (ii) In order to do in a simpler way, as proposed, I should have an estimation about how many of the actives cases are in ICUs.

**Pull request closed without merging**
