### PR TITLE
Merge Adrianturcato's New Viz

### PR DESCRIPTION
**Pull request by hamelsmu**
@all-contributors add @adrianturcato for content

### CODE REVIEW

**Comment by hamelsmu** [comment]
@adrianturcato  I didn't even know you could do this in Jupyter Notebooks this is amazing.  @pratapvardhan seems like you would like this viz

cc: @zachmayer @dansbecker

**Comment by hamelsmu** [comment]
@all-contributors add @adrianturcato for content

**Comment by pratapvardhan** [comment]
Nice work @adrianturcato! CSSEGISandData is going to drop recovered cases, this would make analysis updates a bit tricky..

**Comment by adrianturcato** [comment]
@pratapvardhan thanks for the heads, I will have to think of a way around that

**Pull request merged**
