### PR TITLE
Added overview nb for Australia + Improved the design template

### PR DESCRIPTION
**Pull request by iamashks**
Hi, I added an overview notebook for Australia showing state-wise data of COVID-19. Also:

- I added recovered-cases data in the overview page.
- I tried to make the design better -- clean and modern. _I did it for Australia, and the plan is to update the design for rest of the overview pages after getting your feedback._

You can check the original [repo](https://github.com/iamashks/covid19-australia) and the new design in the screenshot below.

index

Let me know if you find the changes useful. I'm happy to update per your feedback.

Thank you,
Ash

### CODE REVIEW

**Comment by hamelsmu** [comment]
@pratapvardhan are you okay with these changes?

**Comment by hamelsmu** [comment]
I'm going to go ahead and close this PR as the changes were only made for Australia, however I think you need to work with @pratapvardhan to propose/make changes to the other dashboards and make them all look consistent.  

Look forward to your work on this, thank you

**Comment by iamashks** [comment]
@hamelsmu Thank you. I will try to reach @pratapvardhan.

**Comment by iamashks** [comment]
@hamelsmu I couldn't reach @pratapvardhan. Could you accept if I make changes to all the dashboards and make them all look consistent without changing Pratap's analysis/logic? Thanks!

**Comment by hamelsmu** [comment]
Can you just change the blue buttons at the top?  Perhaps you don't need to change the entire look of the rest of the dashboard?

Thoughts?

**Comment by iamashks** [comment]
@hamelsmu I really like the new look of the dashboard (see it live [here](https://jsfiddle.net/4shr7zjg/)). But I understand if you'd like to stick to the current look & feel. That said, I'm good with any of the look - old or new (or just with the blue buttons). What do you suggest?

**Comment by pratapvardhan** [comment]
@iamashks -- I'm aligned with not making changes to design.

- Can you reuse `covid_overview.py` and remove portions of code which can be reused?
- I'd prefer `Updated meta` on top, unlike this cases, other tables have many rows, and would like to this refresh date right at top.

**Comment by iamashks** [comment]
@pratapvardhan Thank you for sharing your thoughts.

I get your point. Could you explain these:
- "remove portions of code which can be reused": do you mean "re-use which can be re-used"?
- "unlike this cases, other tables have many rows": could you clarify this point, please?

Also, I shall keep the old design as well as color styles in my dashboard, right?

**Comment by hamelsmu** [comment]
I'll weigh in here:

1.  Let's keep all the original styling
2. The only styling that should change is we should adopt your blue buttons

Thanks

**Comment by pratapvardhan** [comment]
@iamashks -- Sorry, that was hard to read. Let me clarify :-)

- If you check [covid_overview.py](https://github.com/github/covid19-dashboard/blob/master/_notebooks/covid_overview.py#L23) -- it had a bunch of functions. can `get_template` and `get_frame` be used instead of your local functions? See [Europe notebook](https://github.com/github/covid19-dashboard/blob/master/_notebooks/2020-03-21-covid19-overview-europe.ipynb) for reference.
- Likewise, you can probably use `gen_data` with `filter_frame = lambda x: x['Country/Region'] == 'Australia'`? This basically reduces all the code used for aggregations.
- This text `UPDATED ON APRIL 29, 2020 ( +CHANGE SINCE 5 DAYS AGO.)` on https://covid19dashboards.com/covid-overview/ is better suited to be kept above the table than below. (Like it is currently). You're changing this to bottom of the table?

**Comment by iamashks** [comment]
@hamelsmu Thanks for your feedback.

@pratapvardhan Thanks for explaining. I will update my NB accordingly.

**Pull request closed without merging**
