### PR TITLE
add new notebook on estimating the number of infected as suggest by @dansbecker

### PR DESCRIPTION
**Pull request by jbduarte**
This is vital info!

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jbduarte  please remove the file `_notebooks/2020-03-19-cases-and-deaths-per-million.ipynb` from this commit history as that has nothing to do with this PR.

I added a [Contributing Guide](https://github.com/github/covid19-dashboard/blob/master/CONTRIBUTING.md) if you could follow that closely that would be helpful.  You have to also change two other files per the example PR in that guide, as well as provide a picture for your image card preview (see other notebooks that save an image that is linked to the front matter), which you should be generating programmatically.   You mention `images/covid-infectedVScases.png` but you don't save that anywhere, this image must be saved using a relative path so from your notebook it would be `..i/mages/covid-infectedVScases.png`

Please test the look and feel of your dashboard locally by running

`make build` followed by `make server`. 

1. Pay special attention to the naming convention of all the other notebooks in this repo.  Please follow that

2. There is a fair amount of code that is repeated in the notebook.  This might get hard to maintain over time, can you refactor this into functions so we aren't copying and pasting the same code for each graph?  The last notebook you did had this issue but I would rather not keep repeating this, as this causes a maintenance headache. 

3. To use laTeX you must set `set_math` to `true` in `_config.yml` https://github.com/github/covid19-dashboard/blob/master/_config.yml#L51

4.  I'm not a `LaTex` expert but I'm getting this error when trying to render your page

```
Liquid Exception: Liquid syntax error (line 20): Variable '{{CFR}' was not properly terminated with regexp: /\}\}/ in /data/_posts/2020-03-20-estimating_#infected.md
```

Does that mean anything to you?

5.  The pharse `Since Outbreak` seems superfluous, Try to find a way to shorten your chart title as it is quite long.  Perhaps the words `Habitants,  `outbreak`, `COVID-19` elsewhere in your axis titles are superfluous too


6. This chart is overwelmed by the scale of China, perhaps you should exclude China or put China in a seperate graph

image


7. It is not clear how this chart is part of the story of the dashboard.  Suggest moving it into an appendix section with some notes about how this is relevant to estimating the number of cases from the death rate.  Perhaps this can be clarified with better headings if it is relevant.  See number 9 below.

image

8.  The first thing that appears in your dashboard is a background of (useful) methodology about how this is calculated, followed by a table, followed by your first visualization.  Per the contributing guide, please put your visualization first, followed by the table, and then explain your methodology below.  

9.  You have two sets of charts, you have 2 plots followed by a table and then another 2 plots followed by a table.  Can you orgainze/divide these into sections?  
image

image

**Comment by hamelsmu** [comment]
@drscotthawley How did you include LaTex in fastpages without it breaking the build?  Any tips here?

**Comment by hamelsmu** [comment]
@jbduarte for your Latex, you might have to surround it on both sides with raw tags

```
{% raw %}
  Your LaTeX
{% endraw %}
```

**Comment by hamelsmu** [comment]
Don't worry about the conflicts.  That is really difficult I will fix that for you.  Also, if you need help with anything please don't be shy.  Thanks again for presenting this information ❤️

**Comment by jbduarte** [comment]
Dear Hamel,

I am fixing them at the moment.

I shroud able to finish in one hour.

Thanks

**Comment by hamelsmu** [comment]
@jbduarte  No worries just wanted to express my support.  Please take as long as you need

**Comment by jbduarte** [comment]
Thanks a ton.

J

**Comment by drscotthawley** [comment]
@hamelsmu  Wow, that looks like really basic math, i.e. the equations aren't using any complicated constructions..  Fastpages ought to handle equations like that with no added work required of the user; and if it can't, then there's a problem.   

I did nothing special, all I ever did was just set `use_math` to `true` in the config file. 

I'm not sure what's going on, but I suspect that, as per my experience, `nbdev` is somehow mangling the LaTeX code that it should just leave alone, and then, because both LaTex and Liquid seem to rely on curly braces a lot, Liquid is getting confused.  Looking at the output from nbdev would be the way to check.

I would advocate having nbdev do *nothing* to any expression contained in double dollar signs ($$...$$) within 'text' cells of the notebook -- just have it leave them alone.

**Comment by hamelsmu** [comment]
Yeah, unfortunately, Liquid is omnipresent so if you have double curly braces, you have to escape it, somehow.  And we are relying on liquid in markdown for other magic, so the only way is to escape this with raw tags.  This is the case of two markup languages (LaTex and Liquid) colliding with eachother, and you have to tell the controlling one, Liquid, to please ignore stuff.

**Comment by hamelsmu** [comment]
@jbduarte I'm afraid you may have not read my feedback carefully, as there still only appears to be a single notebook without any supporting files.  I can try to fix this time, however it will be difficult for me to keep doing this ... thanks for understanding

**Comment by drscotthawley** [comment]
@hamelsmu  I wonder, could the escaping be done automatically? such as...

```
$$ ... $$
```
gets automatically replaced with
```
{{% raw %}}
$$ ... $$
{{% endraw %}}
```
?

**Comment by hamelsmu** [comment]
@drscotthawley I was just thinking the same thing!  Yes you are right I think it can!  Would you do me a favor an open an issue in nbdev for this?  Great idea

**Comment by jbduarte** [comment]
@hamelsmu My apologies. I forgot to save the figure for instance. Do you want me to fix this or you are on top of it? Sorry to give you so much work.

**Comment by hamelsmu** [comment]
This has been closed by https://github.com/github/covid19-dashboard/pull/92

**Comment by hamelsmu** [comment]
@jbduarte I see from the history that you had started to work on this at the same time.  Sorry about that I took it over and started to fix things.  You can take a look at what is in production and let me know if you have any concerns

**Pull request closed without merging**
