### PR TITLE
Contact Page

### PR DESCRIPTION
**Pull request by bhutkeyur**
This form will help users to send messages directly to the GitHub support email.

### CODE REVIEW

**Comment by hamelsmu** [comment]
Why do we need this?  I don't think it is necessary

**Comment by bhutkeyur** [comment]
> Why do we need this? I don't think it is necessary

I think it will help users to get support directly and not to search for the specified contact page; also if they want to report any bugs or errors and are not familiar with git they can help.

**Comment by hamelsmu** [comment]
I Understand. In this case I am the support and need to funnel things
through issues.  Ideas are welcome in how to do this without increasing the
maintenance burden

Cheers

**Comment by hamelsmu** [comment]
I thought about this mroe and will reopen this PR while I think about how to integrate this into the page a bit more

**Comment by hamelsmu** [comment]
I think what I'll do is just put a link to opening an issue on the About page, I spoke to some people and support@github.com is not an appropriate mechanism to use here.  

Thanks for the input, though!

**Comment by bhutkeyur** [comment]
Can you please tell me what email should be put up there so that I can fix it.

**Comment by hamelsmu** [comment]
you need to open an issue there is no support email

**Pull request closed without merging**
