### PR TITLE
Cases and deaths scaled by population size now with Altair

### PR DESCRIPTION
**Pull request by jbduarte**

### CODE REVIEW

**Comment by hamelsmu** [comment]
Thanks, @jbduarte!  We probably would want to have the ability to **filter** the visualization by clicking on the legend instead, for example, you can see this: https://covid19dashboards.com/compare-country-trajectories/

P.S. if you want to continue working on this, may I kindly suggest pulling the latest version of your notebook currently in master as some important changes (like moving things to appendix, changing the title, etc have also been made). 

Thanks so much for your contributions!

**Comment by jbduarte** [comment]
Yes. I made those in my latest version. I will make a PR.

Thanks!

J

**Comment by hamelsmu** [comment]
Ok shall I close this PR?  Or will you open a new one?  🙇

**Comment by jbduarte** [comment]
You can close. I open a new one. Thanks!

**Pull request closed without merging**
