### PR TITLE
Reopen "Add progress-projections dashboard"

### PR DESCRIPTION
**Pull request by artdgn**
Trying to reopen https://github.com/github/covid19-dashboard/pull/232. 
For some reason this PR is only for one recent commit, I couldn't open a PR with the reverted commits (revered https://github.com/github/covid19-dashboard/pull/245). Not sure how to reopen with the reverted commits.

### CODE REVIEW

**Comment by artdgn** [comment]
I've rebased and it seems ok now (although contains some files that don't belong to my changes). @hamelsmu I've also added a long response to your last comment in the closed PR.

**Comment by hamelsmu** [comment]
@dansbecker want to take a final look at this?

**Comment by dansbecker** [comment]
I won't be able to take a close look... just flipping through and seeing if I can correctly understand the tables:

image


What's the numerator and denominator here in estimated affected population percentage for the US? I don't think 660k/.004 is the US population. 

I'm guessing the numerator in 0.4% is all cases, not just those infected in the last 5 days? If that's right, it's not totally clear.

Projected in next 14 days is fraction of population. I think I've got that. Reported fatality rates of ~10%... I assume is correct, even though it's far higher than I'd realized :(


In the lower table, I thought I'd read somewhere that you @hamelsmu and @artdgn decided not to include 60 day projections because it's all too far out. Did I misunderstand that? FWIW, I'm skeptical these are right... not because the model is bad... I just think the error bars for any 60 day estimate by anyone right now would be huge:

image

I also would have guessed the ordering of columns is 
cases ->  affected population -> ICU -> Death

I'm not sure I have affected population in the right place, but if you ignore that column, it feels like I'm reading in an order that mirrors the progression. That's easier for me to parse personally.

**Comment by artdgn** [comment]
@dansbecker Thanks taking a look:

> I'm guessing the numerator in 0.4% is all cases, not just those infected in the last 5 days? If that's right, it's not totally clear.

Added clarification in column names for new vs. total.

--------------

> I just think the error bars for any 60 day estimate by anyone right now would be huge

Agree, removed.

--------------

> cases -> affected population -> ICU -> Death

My logic was to present from most reliable to most speculative (death reports being most reliable, than cases, than estimations and projections). But I see your point, and have reordered in your proposed order. The one slight issue that I have with both of those orderings is that the sort column is not the first one - it's sorted by estimated ICU need in 14 days. The reason it's sorted by this, is that to me it seems that this is the number that conveys most the order of severity of the situation in near future.

**Comment by hamelsmu** [comment]
@all-contributors add @artdgn for content

**Comment by hamelsmu** [comment]
@artdgn i'm still having trouble reading the dashboard.  I apologize for the number of comments, but this is the inherent trouble of packing way too much information into a visualization.  The dashboard we are reviewing has way too much going on.  I think less is more, and this is where I believe we are really struggling.

I want to challenge or push on the notion of calculating the % of ICU Spare capacity per 100k.  Can we show this metric instead of the two numbers where the reader has to compare two numbers and do the mental math themselves?  this also has the effect of reducing the number of columns in the table.  I understand that ICU capacity is not always available, but you have a detailed table right before the appendix which shows all the numbers anyway, so the user can find the raw numbers there?  Suggested columns

- Current ICU spare capacity utilized
- Projected in 14 days
- Projected in 30 days
- ICU capacity per 100k
- The estimated daily case growth rate

Also to address @dansbecker 's point

> In the lower table, I thought I'd read somewhere that you @hamelsmu and @artdgn decided not to include 60 day projections because it's all too far out. Did I misunderstand that?

Can you remove the 60 day projection here?  I would say keep it, except we are not displaying any measure of uncertainty in these diagrams so I tend to agree with Dan in this case

**Comment by artdgn** [comment]
@hamelsmu thanks for adding as contrinutor :+1: .

> I want to challenge or push on the notion of calculating the % of ICU Spare capacity per 100k

Just in case you missed it, I'm assuming you've read my response in the closed PR: https://github.com/github/covid19-dashboard/pull/232#issuecomment-607811707 . 
My current main concerns are:
 - Mainly, I trust this ratio less than the added need for ICU beds itself. This is due to the added layers of speculations and assumptions (the ICU data is accurate, that occupancy is close to 70%, that capacity is distributed geographically in the same way as the infection). I think it gives a useful order of magnitude for the capacity of a country, but I have a strong hunch that it is too optimistic (because it's not the only bottleneck, and it's not easily utilized due to geography). For example: Italy was having a crisis when it was below 0.5 added ICU need per 100k. Despite having 2.9 spare capacity in this table. I suspect this is due to older population increasing the nominal occupancy, and due to the geographical concentration of the infection. I do find this is a very useful data point, but I don't trust it enough to bake it into the most important number in the dashboard as you're suggesting.
 - Also, sorting and selecting by this ratio will be arbitrary due to the need for imputation. The table is a Top-20 table, and so an important part is not only the columns, but also the rows. The row selection is currently done on added ICU need. I think this is more fair to countries with no ICU data because these calculation don't depend on external data to COVID-19 data (except populations).
- If no imputation is performed, the table will just have to omit all the countries without ICU beds data, and this is also unfair (due to those countries with that data mainly being the richest countries). 

Sorry for pushing back on this, but I've tried calculating and resorting according to that, and I've tried getting more data / imputing. I just didn't like any of the attempts, and felt less confident about the results.

-----------------

> Can you remove the 60 day projection here? 

I believe I've already removed it following @dansbecker 's comments. Do you still see it in the dashboard?

------------

>  The dashboard we are reviewing has way too much going on.

Perhaps the dashboard could be split into several. Or have some kind of tab / lateral mechanism instead of the linear one. What do you think?

------------

I might repeat myself, but I think that better results might come from getting additional input / ideas from potential users of the dashboard and iterating on it after an initial solid version is shipped.

**Comment by hamelsmu** [comment]
Sounds good -- It sounds like we should make a decision to merge/not merge based on what we have here, as we have been through quite a bit of back and forth.  I'll be able to review on Monday

**Comment by hamelsmu** [comment]
I've made some significant editorial changes to your notebook, namely I am completely hiding the "% of population affected" to try and limit the amount of information presented.

**Comment by artdgn** [comment]
> I've made some significant editorial changes to your notebook, namely I am completely hiding the "% of population affected" to try and limit the amount of information presented.

That's great, thanks. I do appreciate it.

Have to mention though that it'd be fair for me to at least be a reviewer on that PR, especially considering the attribution text that was changed (and the lack of mention of the significant editorial changes). I'll make some minor changes in a separate PR if you don't mind.

It looks indeed less busy, which is great. Would you mind the other (hidden) table as another / separate dashboard page (linking to this one for docs / appendix)? Or maybe as a collapsible hidden element?

**Comment by hamelsmu** [comment]
Sorry about that!  I was trying to avoid the PR fatigue that I'm afraid I put you through.  

Can I change anything about attribution to make it better?  This is one area that is really important to me.  If I recall correctly, I added an additional link to your name with my edits because I felt like it was hard to find you.  Anyhow, let me know if I can change something on that front.  Please feel free to make a PR to tweak it if necessary. 

I think your idea of putting it under a collapsable element is a good idea, I'll open a PR to add that in and get your review.

> Have to mention though that it'd be fair for me to at least be a reviewer on that PR, especially considering the attribution text that was changed (and the lack of mention of the significant editorial changes). I'll make some minor changes in a separate PR if you don't mind.

**Pull request merged**
