### PR TITLE
Added a standalone overview page for Australia

### PR DESCRIPTION
**Pull request by iamashks**
Hi,

I'm continuing from https://github.com/github/covid19-dashboard/pull/250, but I'd request to add it as a standalone notebook/page as I'd like to keep the new design for Australia.

I added an overview page for Australia showing state-wise data of COVID-19. Also:

- I added recovered-cases data in the overview page.
- I tried to make the design better -- clean and modern.
- I added some graphs using Plotly for easy visualization.

You can check the [original repo](https://github.com/iamashks/covid19-australia) and the updated design along with the interactive graphs built using Plotly in the screenshot below.

Please let me know what you think about it.

Thank you, Ash.

2020-05-16 07 52 59 localhost 4334a2370445

### CODE REVIEW

**Comment by hamelsmu** [comment]
Hi totally understand the desire to have a separate page, however my job is to drive some level of conformity on these dashboards so there isn't a confusing explosion of redundant information and places to find the same information.  

I think that it would be best to make things consistent overall instead of dedicating a page with slightly different styling for one country

**Comment by hamelsmu** [comment]
@iamashks I would also request that you fix the notebook on the current page as it is broken.  I am temporarily removing it by placing it in the drafts folder

**Comment by iamashks** [comment]
Hi @hamelsmu, thanks for your feedback. I consider your earlier feedback, but I see there are other similar pages too which shows specific country dashboard + other information:

- https://covid19dashboards.com/covid-overview-morocco/
- https://covid19dashboards.com/jupyter/2020/04/27/Covid-19-Overview-Chile.html

That's the reason I requested a page for Australia too. Please let me know what you think. Thanks!

**Comment by hamelsmu** [comment]
I understand this proposed page is so similar to an existing one that it doesn't make sense to separate it.

**Comment by iamashks** [comment]
Hi @hamelsmu, thanks for your feedback. As you'll see, those other two pages are similar too - they list country/state stats, and in addition, display a few related charts. That's why I added charts.

That said, could you suggest ideas to make this notebook apart? So that it's acceptable as a new page. If not, I totally understand; I will update it to match the current overview page. Thanks!

**Comment by iamashks** [comment]
Hi @hamelsmu, please tell what do you think about my above proposal? Thanks a lot!

**Comment by hamelsmu** [comment]
I still maintain that it needs to be integrated with the other pages due to its similarity

**Pull request closed without merging**
