### PR TITLE
Added dashboard for highest deaths and recovered rates

### PR DESCRIPTION
**Pull request by arungupta21**
Hello, 

Thanks a lot for providing a nice platform to access covid-19 data. his is my first attempt to contribute into an open source. I am excited to share my work. 

Gratitude. Stay safe & healthy

Arun Gupta

### CODE REVIEW

**Comment by arungupta21** [comment]
Hello Team,

May I request you to review the request?

Best
Arun

**Comment by arungupta21** [comment]
Hello Team,

May I request for a review of the pull request?

Best 
Arun

**Comment by hamelsmu** [comment]
Thanks Arun,
  I think your dashboards are interesting, perhaps you can put these in one of the existing dashboards on https://covid19dashboards.com/ as the content is not widely different 

What do you think?

**Comment by arungupta21** [comment]
> Thanks Arun,
> I think your dashboards are interesting, perhaps you can put these in one of the existing dashboards on https://covid19dashboards.com/ as the content is not widely different
> 
> What do you think?

Sounds good. Thanks for your positive feedback.
I would add these visualazations to https://covid19dashboards.com/covid-compare-permillion/.

If that if fine by you, I will merge the changes to 2020-03-19-cases-and-deaths-per-million.ipynb and create another PR.

Your inputs?

**Comment by hamelsmu** [comment]
Arun that sounds like an excellent idea.  Looking forward to your PR

I'll close this one in the meantime.  Thanks for contributing!

**Pull request closed without merging**
