### PR TITLE
Titles consistent

### PR DESCRIPTION
**Pull request by hamelsmu**
@pratapvardhan I am merging your dashboard into one, since they have similar content.

### CODE REVIEW

**Comment by pratapvardhan** [comment]
I was thinking if we should have a toggle between separate pages? (World, US, Europe/&Asia?) 
image

Having everything in one page would make it pretty long page to scroll? What do you think?

I'd lean on having separate pages. And, I understand if you think it's best to stick to World and US for now. I'll leave it to you to decide.

**Comment by hamelsmu** [comment]
Toggle would be cool!  Is there a way to do that?

**Comment by pratapvardhan** [comment]
If you're okay to have separate notebooks / separate urls for each (World, US, Europe, Asia) we can set that up, it will basically switch between pages. I'm not sure if that's what you'd like though. But if adding multiple notebooks isn't an issue, we can do that.

**Comment by hamelsmu** [comment]
I’m ok with that — do you mind doing a PR for that?  I can make one to the
notebook cards hidden from the home page so best of both worlds!

Set

hidden: true

For the notebook you want to hide on the home page.

What do you think?

**Comment by pratapvardhan** [comment]
Sounds good, I'll send one.

**Pull request merged**
