### PR TITLE
changed `np.log` to `np.log10`

### PR DESCRIPTION
**Pull request by maximelefrancois86**
In the current charts, some countries have a number of confirmed cases per million habitants that is above 10^6. 

This is due to the fact that `np.log` was used. Probably `np.log10` should be used instead.

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jbduarte do you want to allow this change?

**Comment by maximelefrancois86** [comment]
Hi, btw, great work !

This PR should not be merged before checking the result somehow (for some reason I couldn't do this on ReviewNB).

However something clearly needs to be changed anyways.

**Comment by jbduarte** [comment]
No. No country has a number aboce 1300 cases per million. Italy for instance has around 1200 cases per million which gives us ln(1200) ~ 7.09. Also the differences in the natural log allows one to draw some inference on growth rates assuming ln(1+x) ~ x

**Comment by maximelefrancois86** [comment]
What you say is right, Joao. 

However, the Y-scale of this chart says "log of confirmed cases per million"

Which should stand for 2 -> 100. 3 -> 1000 ... 6 -> a million  (impossible to go beyond)

Either we change the scale (Naperian logarithm, usually written ln),  or we change the ln base to 10, usually written log

**Comment by jbduarte** [comment]
I think I understand the misunderstanding here. Both the x axis and the y axis are in linear scale. 
The y label log of (cases per million) which is still a linear value (counter domain of ln function).

But its fine the way it is.

**Comment by hamelsmu** [comment]
closing this PR for now .... feel free to keep discussing ( I am just a moderator )

**Pull request closed without merging**
