### PR TITLE
fix corrupt progress projections notebook

### PR DESCRIPTION
**Pull request by artdgn**
This fixes the notebook.
For some reason local Jekyll is not rendering the interactive plots correctly, but Jekyll in another project (also local) seems to render them correctly, so this might be some kind of local setup issue. In any case, the notebook is ok now.

### CODE REVIEW

**Comment by hamelsmu** [comment]
Thanks for the fix!

**Comment by hamelsmu** [comment]
I get these errors in the browser

image

```
Uncaught ReferenceError: Plotly is not defined
    at covid19dashboards.com/:315
```

```
Uncaught Error: Mismatched anonymous define() module: function(){return function(){return function t(e,r,n){function a(o,s){if(!r[o]){if(!e[o]){var l="function"==typeof require&&require;if(!s&&l)return l(o,!0);if(i)return i(o,!0);var c=new Error("Cannot find module '"+o+"'");throw c.code="MODULE_NOT_FOUND",c}var u=r[o]={exports:{}};e[o][0].call(u.exports,function(t){return a(e[o][1][t]||t)},u,u.exports,t,e,r,n)}return r[o].exports}for(var i="function"==typeof require&&require,o=0;o<n.length;o++)a(n[o]);return a}}()({1:[function(t,e,r){"use strict";var n=t("../src/lib"),a={"X,X div":"direction:ltr;font-family:'Open Sans', verdana, arial, sans-serif;margin:0;padding:0;","X input,X button":"font-family:'Open Sans', verdana, arial, sans-serif;","X input:focus,X button:focus":"outline:none;","X a":"text-decoration:none;","X a:hover":"text-decoration:none;","X .crisp":"shape-rendering:crispEdges;","X .user-select-none":"-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;","X svg":"overflow:hidden;","X svg a":"fill:#447adb;","X svg a:hover":"fill:#3c6dc5;","X .main-svg":"position:absolute;top:0;left:0;pointer-events:none;","X .main-svg .draglayer":"pointer-events:all;","X .cursor-default":"cursor:default;","X .cursor-pointer":"cursor:pointer;","X .cursor-crosshair":"cursor:crosshair;","X .cursor-move":"cursor:move;","X .cursor-col-resize":"cursor:col-resize;","X .cursor-row-resize":"cursor:row-resize;","X .cursor-ns-resize":"cursor:ns-resize;","X .cursor-ew-resize":"cursor:ew-resize;","X .cursor-sw-resize":"cursor:sw-resize;","X .cursor-s-resize":"cursor:s-resize;","X .cursor-se-resize":"cursor:se-resize;","X .cursor-w-resize":"cursor:w-resize;","X .cursor-e-resize":"cursor:e-resize;","X .cursor-nw-resize":"cursor:nw-resize;","X .cursor-n-resize":"cursor:n-resize;","X .cursor-ne-resize":"cursor:ne-resize;","X .cursor-grab":"cursor:-webkit-grab;cursor:grab;","X .modebar":"position:absolute;top:2px;right:2px;","X .ease-bg":"-webkit-transition:background-color 0.3s ease 0s;-moz-transition:background-color 0.3s ease 0s;-ms-transition:background-color 0.3s ease 0s;-o-transition:background-color 0.3s ease 0s;transition:background-color 0.3s ease 0s;","X .modebar--hover>:not(.watermark)":"opacity:0;-webkit-transition:opacity 0.3s ease 0s;-moz-transition:opacity 0.3s ease 0s;-ms-transition:opacity 0.3s ease 0s;-o-transition:opacity 0.3s ease 0s;transition:opacity 0.3s ease 0s;","X:hover .modebar--hover .modebar-group":"opacity:1;","X .modebar-group":"float:left;display:inline-block;box-sizing:border-box;padding-left:8px;position:relative;vertical-align:middle;white-space:nowrap;","X .modebar-btn":"position:relative;font-size:16px;padding:3px 4px;height:22px;cursor:pointer;line-height:normal;box-sizing:border-box;","X .modebar-btn svg":"position:relative;top:2px;","X .modebar.vertical":"display:flex;flex-direction:column;flex-wrap:wrap;align-content:flex-end;max-height:100%;","X .modebar.vertical svg":"top:-1px;","X .modebar.vertical .modebar-group":"display:block;float:none;padding-left:0px;padding-bottom:8px;","X .modebar.vertical .modebar-group .modebar-btn":"display:block;text-align:center;","X [data-title]:before,X [data-title]:after":"position:absolute;-webkit-transform:translate3d(0, 0, 0);-moz-transform:translate3d(0, 0, 0);-ms-transform:translate3d(0, 0, 0);-o-transform:translate3d(0, 0, 0);transform:translate3d(0, 0, 0);display:none;opacity:0;z-index:1001;pointer-events:none;top:110%;right:50%;","X [data-title]:hover:before,X [data-title]:hover:after":"display:block;opacity:1;","X [data-title]:before":"content:'';position:absolute;background:transparent;border:6px solid transparent;z-index:1002;margin-top:-12px;border-bottom-color:#69738a;margin-right:-6px;","X [data-title]:after":"content:attr(data-title);background:#69738a;color:white;padding:8px 10px;font-size:12px;line-height:12px;white-space:nowrap;margin-right:-18px;border-radius:2px;","X .vertical [data-title]:before,X .vertical [data-title]:after":"top:0%;right:200%;","X .vertical [data-title]:before":"border:6px solid transparent;border-left-color:#69738a;margin-top:8px;margin-right:-30px;","X .select-outline":"fill:none;stroke-width:1;shape-rendering:crispEdges;","X .select-outline-1":"stroke:white;","X .select-outline-2":"stroke:black;stroke-dasharray:2px 2px;",Y:"font-family:'Open Sans';position:fixed;top:50px;right:20px;z-index:10000;font-size:10pt;max-width:180px;","Y p":"margin:0;","Y .notifier-note":"min-width:180px;max-width:250px;border:1px solid #fff;z-index:3000;margin:0;background-color:#8c97af;background-color:rgba(140,151,175,0.9);color:#fff;padding:10px;overflow-wrap:break-word;word-wrap:break-word;-ms-hyphens:auto;-webkit-hyphens:auto;hyphens:auto;","Y .notifier-close":"color:#fff;opacity:0.8;float:right;padding:0 5px;background:none;border:none;font-size:20px;font-weight:bold;line-height:20px;","Y .notifier-close:hover":"color:#444;text-decoration:none;cursor:pointer;"};for(var i in a){var o=irequire.min.js:1)
    at T (require.min.js:1)
    at Object.s [as require] (require.min.js:1)
    at requirejs (require.min.js:1)
    at Function.req.config (require.min.js:1)
    at (index):3125
    at (index):3136
```

**Comment by hamelsmu** [comment]
I moved the dashboard back to drafts for the time being 

- I didn't really check the notebook before I merged, my apologies I just merged it b/c I'm familiar with you etc.  I'll check it next time before merging

**Comment by artdgn** [comment]
@hamelsmu @anomal  I've found the problem.
https://github.com/github/covid19-dashboard/commit/b4dc21c5f60602cb0da421bc3fec266104a0eca9 from a couple of days ago in this https://github.com/github/covid19-dashboard/pull/330 "fixes" plotly in a way that breaks its previous usage in this project (e.g. this [plot](https://covid19dashboards.com/us-inflection/#Appendix-USA---Animated-visualization-of-growth) in another notebook is now broken as well). 
Previously plotly figures needed to displayed by `HTML(fig.to_html())` (the solution in https://covid19dashboards.com/us-inflection/) but now they have to be displayed by `fig.show()` (the way @anomal is using it in his notebook). 

Not an expert on plotly or JS, so for now I'll just fix both notebooks (mine and https://covid19dashboards.com/us-inflection/) to use the new way. Are there any other notebooks using plotly (that aren't in `_drafts`)? Maybe later you can decide to revert to use it the previous way (for consistency with fastpages). Or maybe there's a way to to make both usable.

**Comment by hamelsmu** [comment]
Thanks so much for sharing this solution and how you solved it really appreciate it

**Comment by hamelsmu** [comment]
I actually changed fastpages to use the new way ... I’ll check all the dashboards now

**Comment by anomal** [comment]
@artdgn Thanks for fixing the other notebooks. `HTML(fig.to_html()) ` is technically incorrect, because it generates HTML with enclosing `<HTML></HTML>` tags inside the webpage, which would already have the HTML root element. I tried `HTML(fig.to_html()) ` initially, but it prevented `fig.show()` from rendering in nbviewer and local Jupyter (without re-running the cell).  I went through all kinds of combinations to make it work in all three of local Jupyter, nbviewer, and fastpages, and could only make it work on all three by adding the JS dependencies to the fastpages header.  

I also found a weird bug where including `plotly` as a fastpages category prevented nbviewer from including the embedded plotly JS, which prevented graphs from rendering.  This seems like an nbviewer bug?  I don't know if this applies to notebooks in general, but it applied to a draft version of my notebook.

Also, my gender pronoun is "she"/"her".

**Pull request merged**
