### PR TITLE
Estimating effective reproduction number Rt for different provinces across Canada

### PR DESCRIPTION
**Pull request by ujs**
Some time-series charts plotting estimated daily values for effective reproduction number (covid-19) for Canadian provinces. I welcome questions and comments on it.

### CODE REVIEW

**Review by yusuf01019 — APPROVED** [review]
@hamelsmu

**Comment by hamelsmu** [comment]
@anomal would you like to review as someone who is familiar with Canadian data?

**Comment by anomal** [comment]
Notebook Viewer view (better to include in the pull request to make it easier for reviewers): https://nbviewer.jupyter.org/github/ujs/covid19-dashboard/blob/ujs-rt-canada/_notebooks/2020_10_25_reproduction_number_canada.ipynb

Comments: 
1. This is a predictive model--even though it is predicting the past/current reproduction number rather than predicting the future--so the following [guideline](https://github.com/github/covid19-dashboard/blob/master/CONTRIBUTING.md) should be activated:
> Dashboards that present a predictive model will attract additional scrutiny and review. If models are too complex to be understood, or not presented clearly - we may decide it is not appropriate for this site. Furthermore, analysis containing predictive models will be displayed with appropriate warnings to set expectations.

2. I am not an epidemiologist, so I am not sure if this is the correct way to predict Rt. @hamelsmu Do you know someone who is, who can review?

3. I am not sure of the utility of Rt for non-epidemiologists, since according to the graphs, Rt was lower than 0.5, and even close to zero, for some provinces at some points in time, yet Rt shot back up to over 1 or 1.5 later on.

4. Why is `settings.ini` included?

**Comment by ujs** [comment]
@anomal , @hamelsmu - Just FYI, my notebook contains references to my model. I applied the model(which was originally applied to US data by [Kevin Systrom](http://systrom.com/blog/author/ksys1983/)) on Canadian data.

**Comment by anomal** [comment]
Is it normal for epidemiologists to calculate Rt for only a subset of the global population based on a specific geographic region, when there are still cases in the rest of the world that can influence the infection of the regional population?

**Comment by ujs** [comment]
@anomal Local Rt values provide useful information because regional epidemics vary based on many factors, mainly local policy measures like lockdowns, mandatory mask-wearing, travel bans etc. For example- in the US, the pandemic looks very different in California compared to Maine or Texas because of variation in statewide policies. Regional Rt values are used by epidemiologists and policymakers to make decisions about easing restrictions but this metric can have some drawbacks- it is not good at identifying local outbreak clusters impacting a very small subset of the population in the region. This [Nature ](https://www.nature.com/articles/d41586-020-02009-w)article is a good guide to understand Rt pros and cons.

**Comment by hamelsmu** [comment]
Settings.ini as well as changes to other notebooks have been added to this PR, why is that?

**Review by hamelsmu — CHANGES_REQUESTED** [review]
As @anomal mentioned there are irrelevant files added to this PR

**Comment by ujs** [comment]
> Settings.ini as well as changes to other notebooks have been added to this PR, why is that?

@hamelsmu - The settings.ini file was added automatically when I used fastpages (it was inadvertent and I missed it). Also, in one of my previous notebooks, there was an inadvertent change in the python version info. So, do you recommend I make changes to this PR itself. Or, should I submit another pull request on a separate branch (you know, start from scratch to avoid unintended issues like the ones you discovered)?

**Comment by anomal** [comment]
@ujs You should make changes to this PR itself.  

```
git rm --cached settings.ini
```

It might be good to add this file to .gitignore, so that other people don't accidentally add it, so .gitignore should have the following appended to it:

```
settings.ini
```

For the restaurant notebook, from my understanding of [this,](https://stackoverflow.com/questions/215718/how-can-i-reset-or-revert-a-file-to-a-specific-revision) the following should work:
```
git checkout master -- _notebooks/2020_09_07_compare_restaurant_reopenings.ipynb
```

I don't have experience with Rt and can't comment on it further, so these are just technical comments.

**Review by yusuf01019 — APPROVED** [review]

**Comment by ujs** [comment]
changes made as requested

**Comment by hamelsmu** [comment]
@ujs I'm afraid this dashboard in its current form is far too academic and doesn't contain information that is approachable for most people.  

I encourage you to host this dashboard on your own site, perhaps using [fastpages](https://github.com/fastai/fastpages), and I'll be happy to link to it from the [related page](https://github.com/github/covid19-dashboard/blob/master/_pages/related.md).   Since this site uses fastpages, you should only have to copy your notebook into a new fastpages repo you create once you set everything up.

This is not a criticism of your work or how valuable it is.  I must do the difficult job of curating information on this site.  Thanks for understanding.

**Pull request closed without merging**
