### PR TITLE
Add cases per million & positive test rate

### PR DESCRIPTION
**Pull request by jwrichar**
A few additions in this PR:

1. Added "Reported Cases per Million" and "Positive Test Rate" to the table as extra (very interesting IMO!) info for folks to look at:
image

2. Added a new plot that shows the reported and estimated "COVID-19 Case counts per million".  This has a lot more value than the original plot -- for instance, CA is much lower on this scale than some of the denser Northeast states (MA, CT, VT) where relatively little reporting has been done. You can also really see how Louisiana has been hit hard (per capita).
image

3. Small fix to some of the weird behavior from the API -- now using the `states` endpoint for everything except the 7-day lookback.

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jwrichar is this "Estimated Positive Test Rate" or actual Positive Test Rate.  I think its the former?  If so, please name the table accordingly?

**Comment by hamelsmu** [comment]
@jwrichar also I'm not sure the second viz is readable or illluminates any interesting information?  I believe we discussed this plot before?   Has anything changed about this plot since last time? 

Thanks for the submission!

**Comment by hamelsmu** [comment]
Alternatively, you could include a section before the table defining each of the fields.  That might clear things up a bit

**Comment by jwrichar** [comment]
@hamelsmu thanks for the comments.

+ I've shortened the table names to improve legibility and added verbiage to the table description to clearly define each of the columns
+ The plot now shows **cases per million people**, which is a new way of looking at it (before we were showing the raw counts).  I think this is interesting because it gets a bit closer to understanding where the outbreak is the worst on a per-capita basis.  For example, LA is clearly in a much worse status on a per capita basis than CA, even though the latter's overall counts are higher.  I've now sorted that figure by per-million case counts, to improve clarity.

Let me know what you think!

**Comment by hamelsmu** [comment]
I just pushed these changes to master.  Looks good, thanks!

**Pull request closed without merging**
